version: '3'

services:
  auth-service:
    build: .
    container_name: bouncer
    restart: unless-stopped
    env_file:
      - stack.env
    ports:
      - "${PORT}:${PORT}"
    # networks:
    #   - proxy_network

# Розкоментуйте, якщо потрібно підключити до існуючої мережі
# networks:
#   proxy_network:
#     external: true
#     name: traefik_proxy  # Замініть на назву вашої мережі
